import { Inter } from "next/font/google";
import "./globals.css";
import ReduxProvider from "@/Redux/ReduxProvider";
import ReactQueryProvider from "./layouts/ReactQueryProvider";
import { ToastContainer } from "react-toastify";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
     <ReduxProvider>
   <ReactQueryProvider>

        {children}
   </ReactQueryProvider>
     </ReduxProvider>
      <ToastContainer />
        </body>
    </html>
  );
}
